LEVELING_CHARACTERS = createHeader({
	readable = "Leveling Characters",
	constant = "LEVELING_CHARACTERS",
	icon = 236565,	-- Level 40 Achievement Icon. If someone has a better idea, go for it.
	text = {
		en = "Leveling Characters",
		-- TODO: de = "",
		es = "Personajes subiendo de nivel",
		mx = "Personajes subiendo de nivel",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		cn = "升级中角色",
		tw = "升級中角色",
	},
	description = {
		en = "Contains things that can be obtained only by characters that are not max level.",
		-- TODO: de = "",
		es = "Contiene objetos que solo pueden obtener los personajes que no hayan alcanzado el nivel máximo.",
		mx = "Contiene objetos que solo pueden obtener los personajes que no hayan alcanzado el nivel máximo.",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		cn = "包含只能由未达到最高等级的角色获得的物品。",
		tw = "包含只能由未達到最高等級的角色獲得的物品。",
	},
});
