SHOWDOWN = createHeader({
	readable = "Showdown",
	icon = 7649260,
	text = {
		en = "Showdown",
		de = "Konfrontationen",
		es = "Confrontación",
		mx = "Confrontación",
		fr = "Épreuve de force",
		it = "Scontro Decisivo",
		ko = "최후의 대결",
		pt = "Confronto Final",
		ru = "Решающая схватка",
		cn = "摊牌",
		tw = "攤牌",
	},
	lore = {
		en = "The worlds of Naigtal and Val are distant frontiers caught in the widening shadow of the Void. Reached only through unstable portals deep within Voidstorm, these realms have become strongholds for powerful enemies directing attacks against Azeroth.",
		-- TODO: de = "",
		es = "Los mundos de Naigtal y Val son fronteras lejanas atrapadas en la creciente sombra del Vacío. Accesibles únicamente a través de portales inestables en las profundidades de la Tormenta del Vacío, estos reinos se han convertido en fortalezas de poderosos enemigos que dirigen ataques contra Azeroth.",
		mx = "Los mundos de Naigtal y Val son fronteras lejanas atrapadas en la creciente sombra del Vacío. Accesibles únicamente a través de portales inestables en las profundidades de la Tormenta del Vacío, estos reinos se han convertido en fortalezas de poderosos enemigos que dirigen ataques contra Azeroth.",
		-- TODO: fr = "",
		-- TODO: it = "",
		-- TODO: ko = "",
		-- TODO: pt = "",
		-- TODO: ru = "",
		-- TODO: cn = "",
		-- TODO: tw = "",
	},
});
