
local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[633908] = {
		readable = "Spirit Urn",
		model = 6870561,
		text = {
			en = "Spirit Urn",
			es = "Urna espiritual",
			mx = "Urna de espíritus",
			de = "Geisterurne",
			fr = "Urne d’esprit",
			it = "Urna Spirituale",
			pt = "Urna Espiritual",
			ru = "Урна душ",
			ko = "영혼 단지",
			cn = "灵魂之瓮",
			tw = "靈魂之甕",
		},
	},
	[633913] = {
		readable = "Petrified Egg",
		model = 6739983,
		text = {
			en = "Petrified Egg",
			es = "Huevo petrificado",
			mx = "Huevo petrificado",
			de = "Versteinertes Ei",
			fr = "Œuf pétrifié",
			it = "Uovo Pietrificato",
			pt = "Ovo Petrificado",
			ru = "Окаменевшее яйцо",
			ko = "석화된 알",
			cn = "石化的卵",
			tw = "石化的蛋",
		},
	},
	[642203] = {
		readable = "Repair Supplies",
		model = 7277205,
		text = {
			en = "Repair Supplies",
			es = "Suministros de reparación",
			mx = "Suministros de reparación",
			de = "Reparaturwerkzeug",
			fr = "Fournitures de réparation",
			it = "Forniture per Riparazioni",
			pt = "Suprimentos de Reparo",
			ru = "Припасы для ремонта",
			ko = "수리용 보급품",
			cn = "修理补给品",
			tw = "修復補給品",
		},
	},
	[655006] = {
		readable = "Wooden Toy Sword",
		model = 5658299,
		text = {
			en = "Wooden Toy Sword",
			es = "Espada de juguete de madera",
			mx = "Espada de madera de juguete",
			de = "Hölzernes Spielzeugschwert",
			fr = "Épée de jeu en bois",
			ru = "Игрушечный деревянный меч",
		},
	},
	[656489] = {
		readable = "Azta'rec Cache",
		model = 7277177,
		text = {
			en = "Azta'rec Cache",
			es = "Alijo de Azta'rec",
			de = "Vorrat von Azta'rec",
			fr = "Cache d’Azta’rec",
			it = "Cassa di Azta'rec",
			pt = "Depósito de Azta'rec",
			ru = "Тайник Азта'река",
		},
	},
	[673428] = {
		readable = "Ula'tek's Ruin",
		model = 8130560,
		text = {
			en = "Ula'tek's Ruin",
		},
	},
	[673657] = {
		readable = "Serpent's Hoard",
		model = 7277206,
		text = {
			en = "Serpent's Hoard",
			es = "Tesoro de sierpe",
			de = "Schlangenhort",
			fr = "Cache du serpent",
			it = "Tesoro del Serpente",
			pt = "Tesouro da Serpente",
			ru = "Змеиное сокровище",
			ko = "뱀의 비축품",
		},
	},
})
do ObjectDB[objectID] = objectData; end
