
local ObjectDB = ObjectDB; for objectID,objectData in pairs({
	[651045] = {
		readable = "Reliquary Stash",
		model = 7277164,
		text = {
			en = "Reliquary Stash",
			es = "Alijo del relicario",
			mx = "Alijo de relicario",
			de = "Reliquienbehälter",
			fr = "Planque du Reliquaire",
			it = "Scorta del Reliquiario",
			pt = "Estoque do Relicário",
			ru = "Тайник Реликвария",
			ko = "성물회 비축품",
			cn = "神圣遗物学会贮藏",
			tw = "聖匣儲物箱",
		},
	},
	[651047] = {
		readable = "Reliquary Stash",
		model = 7277164,
		text = {
			en = "Reliquary Stash",
			es = "Alijo del relicario",
			mx = "Alijo de relicario",
			de = "Reliquienbehälter",
			fr = "Planque du Reliquaire",
			it = "Scorta del Reliquiario",
			pt = "Estoque do Relicário",
			ru = "Тайник Реликвария",
			ko = "성물회 비축품",
			tw = "聖匣儲物箱",
		},
	},
	[651085] = {
		readable = "Ritual Gem",
		model = 1572128,
		text = {
			en = "Ritual Gem",
			es = "Gema ritual",
			mx = "Gema de ritual",
			de = "Ritualedelstein",
			fr = "Gemme rituelle",
			it = "Gemma Rituale",
			pt = "Gema Ritualística",
			ru = "Ритуальный самоцвет",
			ko = "의식의 보석",
			cn = "仪式宝石",
			tw = "儀式寶石",
		},
	},
	[652477] = {
		readable = "Warded Lockbox",
		model = 7277206,
		text = {
			en = "Warded Lockbox",
			es = "Arcón resguardado",
			de = "Geschützte Schließkassette",
			fr = "Coffret protégé",
			it = "Scrigno Protetto",
			pt = "Caixa-forte Protegida",
			ru = "Защищенный сейф",
			ko = "수호 금고",
			cn = "结界锁箱",
			tw = "受保護帶鎖箱",
		},
	},
})
do ObjectDB[objectID] = objectData; end
