<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <Platforms>x64</Platforms>
    <TargetFramework>net8.0</TargetFramework>
    <BaseOutputPath>..\..\.tools\</BaseOutputPath>
    <PublishAot>False</PublishAot>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <PlatformTarget>x64</PlatformTarget>
    <VerifyReferenceAotCompatibility>true</VerifyReferenceAotCompatibility>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)|$(TargetFramework)'=='Release|x64|net8.0'">
    <OutputPath>..\..\.tools\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <Target Name="ValidateCSVCleanerPlatform" BeforeTargets="PrepareForBuild">
    <Error Condition="'$(Platform)' != 'x64'" Text="CSVCleaner supports only the x64 platform in this revision." />
  </Target>
</Project>
