cd /d "..\.tools\"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/01 - Classic Era.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/01 - Classic SOD.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/02 - TBC.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/03 - Wrath.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/04 - Cataclysm.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/classic/05 - Mists of Pandaria.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/forever/.config/forever.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/retail/ptr.config"
"Parser.exe" baseconfig="../.db/standard/.config/retail/retail.config" config="../.db/standard/.config/retail/beta.config"