name: Parser

# Controls when the action will run.
on:
  # Triggers the workflow on each push event
  push:
    branches:
      - '*' # Trigger on all branches
    tags-ignore:
      - '*' # Ignore all tags
    paths:
      - '.contrib/Parser/**'
      - '.contrib/.db/**'
      - '.github/workflows/Parser.yml'
  # Triggers the workflow on each pull request event
  pull_request:
    paths:
      - '.contrib/Parser/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: .contrib/Parser

    steps:
      - uses: actions/checkout@v7

      - parallel:
        - name: Database Parser for Retail
          id: Parse-Retail
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config

        - name: Database Parser for Classic Era
          id: Parse-ClassicEra
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/01 - Classic Era.config"

        - name: Database Parser for Season of Discovery
          id: Parse-ClassicSoD
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/01 - Classic SOD.config"

        - name: Database Parser for The Burning Crusade
          id: Parse-TBC
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/02 - TBC.config"

        - name: Database Parser for Wrath of the Lich King
          id: Parse-WOTLK
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/03 - Wrath.config"

        - name: Database Parser for Cataclysm
          id: Parse-CATA
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/04 - Cataclysm.config"

        - name: Database Parser for Mists of Pandaria
          id: Parse-MOP
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config=".config/classic/05 - Mists of Pandaria.config"

        - name: Database Parser for Forever
          id: Parse-FOREVER
          timeout-minutes: 5
          continue-on-error: true
          shell: cmd
          run: |
            "Parser.exe" auto baseconfig=.config/retail/retail.config config="../.db/forever/.config/forever.config"

      - name: Full Success Check
        shell: pwsh
        run: |
          $results = [ordered]@{
            Retail = '${{ steps.Parse-Retail.outcome }}'
            ClassicEra = '${{ steps.Parse-ClassicEra.outcome }}'
            ClassicSoD = '${{ steps.Parse-ClassicSoD.outcome }}'
            TBC = '${{ steps.Parse-TBC.outcome }}'
            WOTLK = '${{ steps.Parse-WOTLK.outcome }}'
            CATA = '${{ steps.Parse-CATA.outcome }}'
            MOP = '${{ steps.Parse-MOP.outcome }}'
            FOREVER = '${{ steps.Parse-FOREVER.outcome }}'
          }

          Write-Host "Verify all Versions Parsed Successfully..."
          foreach ($result in $results.GetEnumerator()) {
            Write-Host "$($result.Key): $($result.Value)"
          }

          if (@($results.Values | Where-Object { $_ -ne 'success' }).Count -eq 0) {
            Write-Host "✅ All Versions Parsed Successfully"
          } else {
            Write-Host "❌ One or more Parsed Versions Errored"
            exit 1
          }

      - uses: actions/upload-artifact@v7
        with:
          name: db  # Artifact name
          path: db/  # File path to upload
          retention-days: 7
